// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials_meta.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteCredentialMeta = `-- name: DeleteCredentialMeta :exec
DELETE FROM credentials_meta
WHERE key_type = ?
`

func (q *Queries) DeleteCredentialMeta(ctx context.Context, keyType string) error {
	_, err := q.db.ExecContext(ctx, deleteCredentialMeta, keyType)
	return err
}

const getCredentialMeta = `-- name: GetCredentialMeta :one
SELECT
    key_type,
    label,
    last_validated_at,
    masked_suffix,
    probe_summary
FROM credentials_meta
WHERE key_type = ?
`

func (q *Queries) GetCredentialMeta(ctx context.Context, keyType string) (CredentialsMetum, error) {
	row := q.db.QueryRowContext(ctx, getCredentialMeta, keyType)
	var i CredentialsMetum
	err := row.Scan(
		&i.KeyType,
		&i.Label,
		&i.LastValidatedAt,
		&i.MaskedSuffix,
		&i.ProbeSummary,
	)
	return i, err
}

const listCredentialsMeta = `-- name: ListCredentialsMeta :many
SELECT
    key_type,
    label,
    last_validated_at,
    masked_suffix,
    probe_summary
FROM credentials_meta
ORDER BY key_type
`

func (q *Queries) ListCredentialsMeta(ctx context.Context) ([]CredentialsMetum, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialsMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CredentialsMetum{}
	for rows.Next() {
		var i CredentialsMetum
		if err := rows.Scan(
			&i.KeyType,
			&i.Label,
			&i.LastValidatedAt,
			&i.MaskedSuffix,
			&i.ProbeSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCredentialMeta = `-- name: UpsertCredentialMeta :exec
INSERT INTO credentials_meta (
    key_type,
    label,
    last_validated_at,
    masked_suffix,
    probe_summary
) VALUES (
    ?, ?, ?, ?, ?
)
ON CONFLICT(key_type) DO UPDATE SET
    label = excluded.label,
    last_validated_at = excluded.last_validated_at,
    masked_suffix = excluded.masked_suffix,
    probe_summary = excluded.probe_summary
`

type UpsertCredentialMetaParams struct {
	KeyType         string         `json:"key_type"`
	Label           sql.NullString `json:"label"`
	LastValidatedAt sql.NullTime   `json:"last_validated_at"`
	MaskedSuffix    sql.NullString `json:"masked_suffix"`
	ProbeSummary    sql.NullString `json:"probe_summary"`
}

func (q *Queries) UpsertCredentialMeta(ctx context.Context, arg UpsertCredentialMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertCredentialMeta,
		arg.KeyType,
		arg.Label,
		arg.LastValidatedAt,
		arg.MaskedSuffix,
		arg.ProbeSummary,
	)
	return err
}

const upsertCredentialMetaLabel = `-- name: UpsertCredentialMetaLabel :exec
INSERT INTO credentials_meta (key_type, label)
VALUES (?, ?)
ON CONFLICT(key_type) DO UPDATE SET
    label = excluded.label
`

type UpsertCredentialMetaLabelParams struct {
	KeyType string         `json:"key_type"`
	Label   sql.NullString `json:"label"`
}

func (q *Queries) UpsertCredentialMetaLabel(ctx context.Context, arg UpsertCredentialMetaLabelParams) error {
	_, err := q.db.ExecContext(ctx, upsertCredentialMetaLabel, arg.KeyType, arg.Label)
	return err
}
