// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteAllDevices = `-- name: DeleteAllDevices :exec
DELETE FROM devices
`

func (q *Queries) DeleteAllDevices(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDevices)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT
    id,
    site_id,
    mac,
    model,
    name,
    current_fw,
    adoption_state,
    last_seen,
    updated_at
FROM devices
ORDER BY name, id
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Mac,
			&i.Model,
			&i.Name,
			&i.CurrentFw,
			&i.AdoptionState,
			&i.LastSeen,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (
    id,
    site_id,
    mac,
    model,
    name,
    current_fw,
    adoption_state,
    last_seen,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    site_id = excluded.site_id,
    mac = excluded.mac,
    model = excluded.model,
    name = excluded.name,
    current_fw = excluded.current_fw,
    adoption_state = excluded.adoption_state,
    last_seen = excluded.last_seen,
    updated_at = excluded.updated_at
`

type UpsertDeviceParams struct {
	ID            string         `json:"id"`
	SiteID        string         `json:"site_id"`
	Mac           string         `json:"mac"`
	Model         string         `json:"model"`
	Name          sql.NullString `json:"name"`
	CurrentFw     sql.NullString `json:"current_fw"`
	AdoptionState sql.NullString `json:"adoption_state"`
	LastSeen      sql.NullTime   `json:"last_seen"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.ID,
		arg.SiteID,
		arg.Mac,
		arg.Model,
		arg.Name,
		arg.CurrentFw,
		arg.AdoptionState,
		arg.LastSeen,
		arg.UpdatedAt,
	)
	return err
}
