// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: firmware_manifest.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getFirmwareManifest = `-- name: GetFirmwareManifest :one
SELECT
    id,
    model,
    version,
    url,
    sha256,
    source_url,
    pinned_at,
    verified,
    notes
FROM firmware_manifest
WHERE id = ?
`

func (q *Queries) GetFirmwareManifest(ctx context.Context, id int64) (FirmwareManifest, error) {
	row := q.db.QueryRowContext(ctx, getFirmwareManifest, id)
	var i FirmwareManifest
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.Version,
		&i.Url,
		&i.Sha256,
		&i.SourceUrl,
		&i.PinnedAt,
		&i.Verified,
		&i.Notes,
	)
	return i, err
}

const insertFirmwareManifest = `-- name: InsertFirmwareManifest :one
INSERT INTO firmware_manifest (
    model,
    version,
    url,
    sha256,
    source_url,
    pinned_at,
    verified,
    notes
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id
`

type InsertFirmwareManifestParams struct {
	Model     string         `json:"model"`
	Version   string         `json:"version"`
	Url       string         `json:"url"`
	Sha256    string         `json:"sha256"`
	SourceUrl sql.NullString `json:"source_url"`
	PinnedAt  sql.NullTime   `json:"pinned_at"`
	Verified  sql.NullBool   `json:"verified"`
	Notes     sql.NullString `json:"notes"`
}

func (q *Queries) InsertFirmwareManifest(ctx context.Context, arg InsertFirmwareManifestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFirmwareManifest,
		arg.Model,
		arg.Version,
		arg.Url,
		arg.Sha256,
		arg.SourceUrl,
		arg.PinnedAt,
		arg.Verified,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listFirmwareManifest = `-- name: ListFirmwareManifest :many
SELECT
    id,
    model,
    version,
    url,
    sha256,
    source_url,
    pinned_at,
    verified,
    notes
FROM firmware_manifest
ORDER BY model, version
`

func (q *Queries) ListFirmwareManifest(ctx context.Context) ([]FirmwareManifest, error) {
	rows, err := q.db.QueryContext(ctx, listFirmwareManifest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FirmwareManifest{}
	for rows.Next() {
		var i FirmwareManifest
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Version,
			&i.Url,
			&i.Sha256,
			&i.SourceUrl,
			&i.PinnedAt,
			&i.Verified,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
