// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type ActionLog struct {
	ID          int64          `json:"id"`
	DeviceID    string         `json:"device_id"`
	FromVersion sql.NullString `json:"from_version"`
	ToVersion   sql.NullString `json:"to_version"`
	ManifestID  sql.NullInt64  `json:"manifest_id"`
	InitiatedAt sql.NullTime   `json:"initiated_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	Result      sql.NullString `json:"result"`
	ErrorDetail sql.NullString `json:"error_detail"`
}

type CommunityAnalysis struct {
	PostUrl        string       `json:"post_url"`
	ContentHash    string       `json:"content_hash"`
	ConfidenceJson string       `json:"confidence_json"`
	AnalyzedAt     sql.NullTime `json:"analyzed_at"`
}

type CredentialsMetum struct {
	KeyType         string         `json:"key_type"`
	Label           sql.NullString `json:"label"`
	LastValidatedAt sql.NullTime   `json:"last_validated_at"`
	MaskedSuffix    sql.NullString `json:"masked_suffix"`
	ProbeSummary    sql.NullString `json:"probe_summary"`
}

type Device struct {
	ID            string         `json:"id"`
	SiteID        string         `json:"site_id"`
	Mac           string         `json:"mac"`
	Model         string         `json:"model"`
	Name          sql.NullString `json:"name"`
	CurrentFw     sql.NullString `json:"current_fw"`
	AdoptionState sql.NullString `json:"adoption_state"`
	LastSeen      sql.NullTime   `json:"last_seen"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	InScope       int64          `json:"in_scope"`
	ScopeLostAt   sql.NullTime   `json:"scope_lost_at"`
}

type FirmwareManifest struct {
	ID        int64          `json:"id"`
	Model     string         `json:"model"`
	Version   string         `json:"version"`
	Url       string         `json:"url"`
	Sha256    string         `json:"sha256"`
	SourceUrl sql.NullString `json:"source_url"`
	PinnedAt  sql.NullTime   `json:"pinned_at"`
	Verified  sql.NullBool   `json:"verified"`
	Notes     sql.NullString `json:"notes"`
}

type Preference struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
