// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: preferences.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getPreference = `-- name: GetPreference :one
SELECT
    key,
    value,
    updated_at
FROM preferences
WHERE key = ?
`

func (q *Queries) GetPreference(ctx context.Context, key string) (Preference, error) {
	row := q.db.QueryRowContext(ctx, getPreference, key)
	var i Preference
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertPreference = `-- name: UpsertPreference :exec
INSERT INTO preferences (
    key,
    value,
    updated_at
) VALUES (
    ?, ?, ?
)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type UpsertPreferenceParams struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertPreference, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
