// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DatabasePath():Promise<string>;

export function DatabaseReady():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;
