// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DatabasePath() {
  return window['go']['main']['App']['DatabasePath']();
}

export function DatabaseReady() {
  return window['go']['main']['App']['DatabaseReady']();
}

export function DevKeychainDelete(arg1) {
  return window['go']['main']['App']['DevKeychainDelete'](arg1);
}

export function DevKeychainList() {
  return window['go']['main']['App']['DevKeychainList']();
}

export function DevKeychainSave(arg1, arg2) {
  return window['go']['main']['App']['DevKeychainSave'](arg1, arg2);
}

export function DevKeychainVerify(arg1) {
  return window['go']['main']['App']['DevKeychainVerify'](arg1);
}

export function DevKeychainWipeAll() {
  return window['go']['main']['App']['DevKeychainWipeAll']();
}

export function GetDeviceSettings() {
  return window['go']['main']['App']['GetDeviceSettings']();
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function ListCredentialSlots() {
  return window['go']['main']['App']['ListCredentialSlots']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function RefreshInventory() {
  return window['go']['main']['App']['RefreshInventory']();
}

export function RemoveCredential(arg1) {
  return window['go']['main']['App']['RemoveCredential'](arg1);
}

export function SaveCredential(arg1) {
  return window['go']['main']['App']['SaveCredential'](arg1);
}

export function SaveDeviceSettings(arg1) {
  return window['go']['main']['App']['SaveDeviceSettings'](arg1);
}

export function SyncCredentialSiteSlots(arg1) {
  return window['go']['main']['App']['SyncCredentialSiteSlots'](arg1);
}

export function ValidateCredential(arg1) {
  return window['go']['main']['App']['ValidateCredential'](arg1);
}
