// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function DatabasePath():Promise<string>;

export function DatabaseReady():Promise<boolean>;

export function GetDeviceSettings():Promise<settings.DeviceSettings>;

export function SaveDeviceSettings(arg1:settings.DeviceSettings):Promise<void>;
