// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {settings} from '../models';
import {inventory} from '../models';

export function DatabasePath():Promise<string>;

export function DatabaseReady():Promise<boolean>;

export function DevKeychainDelete(arg1:string):Promise<void>;

export function DevKeychainList():Promise<Array<main.CredentialEntry>>;

export function DevKeychainSave(arg1:string,arg2:string):Promise<void>;

export function DevKeychainVerify(arg1:string):Promise<boolean>;

export function DevKeychainWipeAll():Promise<void>;

export function GetDeviceSettings():Promise<settings.DeviceSettings>;

export function IsDevMode():Promise<boolean>;

export function ListCredentialSlots():Promise<Array<main.CredentialSlot>>;

export function ListDevices():Promise<Array<inventory.Device>>;

export function RefreshInventory():Promise<Array<inventory.Device>>;

export function RemoveCredential(arg1:string):Promise<void>;

export function SaveCredential(arg1:main.SaveCredentialRequest):Promise<main.CredentialSlot>;

export function SaveDeviceSettings(arg1:settings.DeviceSettings):Promise<void>;

export function SyncCredentialSiteSlots(arg1:Array<main.DiscoveredSite>):Promise<Array<main.CredentialSlot>>;

export function ValidateCredential(arg1:string):Promise<main.CredentialSlot>;
