// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DatabasePath() {
  return window['go']['main']['App']['DatabasePath']();
}

export function DatabaseReady() {
  return window['go']['main']['App']['DatabaseReady']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
